export type AutoCompleteSearchAll = {
  zip: string;
  address: string;
  city: string;
  searchType: string;
  stateId: string;
  latitude: number;
  county: string;
  fips: string;
  title: string;
  house: string;
  countyId: string;
  street: string;
  location: string;
  id: string;
  state: string;
  apn: string;
  longitude: number;
};

export type AutoCompleteSearch = {
  city: string;
  searchType: string;
  state: string;
  title: string;
  stateName?: string;
  zip?: string;
  neighborhoodType?: string;
  neighborhoodName?: string;
  neighborhoodId?: string;
};

type PropertySearchAddress = {
  address: string;
  city: string;
  county: string;
  state: string;
  street: string;
  zip: string;
};

export type PropertySearch = {
  // custom field
  isActive?: boolean;
  absenteeOwner: boolean;
  address: PropertySearchAddress;
  adjustableRate: boolean;
  airConditioningAvailable: boolean;
  apn: string;
  assessedImprovementValue: number;
  assessedLandValue: number;
  assessedValue: number;
  assumable: boolean;
  auction: boolean;
  auctionDate: string | null;
  basement: boolean;
  bathrooms: number;
  bedrooms: number | null;
  cashBuyer: boolean;
  corporateOwned: boolean;
  death: boolean;
  deck: boolean;
  deckArea: number;
  equity: boolean;
  equityPercent: number;
  estimatedEquity: number;
  estimatedValue: number;
  floodZone: boolean;
  floodZoneDescription: string;
  floodZoneType: string;
  foreclosure: boolean;
  forSale: boolean;
  freeClear: boolean;
  garage: boolean;
  highEquity: boolean;
  id: string;
  inherited: boolean;
  inStateAbsenteeOwner: boolean;
  investorBuyer: boolean;
  judgment: boolean;
  landUse: string;
  lastMortgage1Amount: number | null;
  lastSaleAmount: string | null;
  lastSaleDate: string;
  lastUpdateDate: string;
  latitude: number;
  lenderName: string | null;
  listingAmount: number | null;
  longitude: number;
  lotSquareFeet: number;
  mailAddress: PropertySearchAddress;
  medianIncome: string;
  MFH2to4: boolean;
  MFH5plus: boolean;
  mlsActive: boolean;
  mlsCancelled: boolean;
  mlsFailed: boolean;
  mlsHasPhotos: boolean;
  mlsLastSaleDate: string;
  mlsListingPrice: number | null;
  mlsPending: boolean;
  mlsSold: boolean;
  negativeEquity: boolean;
  openMortgageBalance: number;
  outOfStateAbsenteeOwner: boolean;
  owner1FirstName: string;
  owner1LastName: string;
  owner2FirstName: string;
  owner2LastName: string;
  ownerOccupied: boolean;
  patio: boolean;
  patioArea: number;
  pool: boolean;
  poolArea: number;
  portfolioPurchasedLast12Months: number;
  portfolioPurchasedLast6Months: number;
  preForeclosure: boolean;
  pricePerSquareFoot: number;
  priorSaleAmount: number | null;
  privateLender: boolean;
  propertyId: string;
  propertyType: string;
  propertyUse: string;
  propertyUseCode: number;
  rentAmount: number | null;
  reo: boolean;
  roomsCount: number;
  squareFeet: number;
  stories: number;
  totalPortfolioEquity: string;
  totalPortfolioMortgageBalance: string;
  totalPortfolioValue: string;
  totalPropertiesOwned: string;
  unitsCount: number;
  vacant: boolean;
  yearBuilt: number;
  yearsOwned: number;
  // custom
  image?: string;
  score?: string;
};

type PropertyDetailsAddress = {
  address: string;
  addressFormat?: string;
  carrierRoute?: string;
  city: string;
  county: string;
  fips: string;
  house: string;
  label: string;
  preDirection?: string;
  state: string;
  street: string;
  streetType?: string;
  unit?: string;
  unitType?: string;
  zip: string;
  zip4?: string;
};

type Demographics = {
  fmrEfficiency: string;
  fmrFourBedroom: string;
  fmrOneBedroom: string;
  fmrThreeBedroom: string;
  fmrTwoBedroom: string;
  fmrYear: string;
  hudAreaCode: string;
  hudAreaName: string;
  medianIncome: string;
  suggestedRent?: string | null;
};

type LastSale = {
  book?: string | null;
  page?: string | null;
  documentNumber?: string | null;
  armsLength?: string | null;
  buyerNames?: string | null;
  documentType?: string | null;
  documentTypeCode?: string | null;
  downPayment?: string | null;
  ltv?: string | null;
  ownerIndividual?: string | null;
  priorOwnerIndividual?: string | null;
  priorOwnerMonthsOwned?: string | null;
  purchaseMethod?: string | null;
  recordingDate?: string | null;
  saleAmount?: string | null;
  saleDate?: string | null;
  sellerNames?: string | null;
  seqNo: number;
  transactionType?: string | null;
};

type LinkedProperties = {
  ids: string[];
  purchasedLast12mos: number;
  purchasedLast6mos: number;
  totalEquity: string;
  totalMortgageBalance: string;
  totalOwned: string;
  totalValue: string;
};

export type LotInfo = {
  apn: string;
  apnUnformatted: string;
  censusBlock: string;
  censusBlockGroup: string;
  censusTract: string;
  landUse: string;
  legalDescription: string;
  legalSection?: string | null;
  lotAcres: string;
  lotNumber?: string | null;
  lotSquareFeet: number;
  propertyClass: string;
  propertyUse: string;
  subdivision?: string | null;
  zoning?: string | null;
};

type OwnerInfo = {
  absenteeOwner?: string | null;
  companyName?: string | null;
  corporateOwned?: string | null;
  equity?: string | null;
  instateAbsenteeOwner?: string | null;
  mailAddress: PropertyDetailsAddress;
  outOfStateAbsenteeOwner?: string | null;
  owner1FirstName: string;
  owner1FullName: string;
  owner1LastName: string;
  owner1Type: string;
  owner2FirstName?: string | null;
  owner2FullName?: string | null;
  owner2LastName?: string | null;
  owner2Type?: string | null;
  ownerOccupied?: string | null;
  ownershipLength: number;
};

export type PropertyAddress = {
  address: string;
  carrierRoute?: string | null;
  city: string;
  congressionalDistrict?: string | null;
  county: string;
  fips: string;
  house: string;
  jurisdiction: string;
  label: string;
  preDirection?: string | null;
  state: string;
  street: string;
  streetType?: string | null;
  unit?: string | null;
  unitType?: string | null;
  zip: string;
  zip4?: string | null;
};

export type PropertyInfo = {
  address: PropertyAddress;
  airConditioningType: string;
  attic?: string | null;
  basementFinishedPercent?: string | null;
  basementSquareFeet: number;
  basementSquareFeetFinished?: number | null;
  basementSquareFeetUnfinished?: number | null;
  basementType: string;
  bathrooms: number;
  bedrooms?: number | null;
  breezeway?: string | null;
  buildingSquareFeet: number;
  buildingsCount?: number | null;
  carport: boolean;
  construction: string;
  deck: boolean;
  deckArea: number;
  featureBalcony?: string | null;
  fireplace: boolean;
  fireplaces: number;
  garageSquareFeet: number;
  garageType?: string | null;
  heatingFuelType?: string | null;
  heatingType: string;
  interiorStructure: string;
  latitude: number;
  livingSquareFeet: number;
  longitude: number;
  lotSquareFeet: number;
  parcelAccountNumber?: string | null;
  parkingSpaces: number;
  partialBathrooms: number;
  patio: boolean;
  patioArea: string;
  plumbingFixturesCount: number;
  pool: boolean;
  poolArea: number;
  porchArea: number;
  porchType: string;
  pricePerSquareFoot: number;
  propertyUse: string;
  propertyUseCode: number;
  roofConstruction: string;
  roofMaterial: string;
  roomsCount: number;
  rvParking: boolean;
  safetyFireSprinklers: boolean;
  stories: number;
  taxExemptionHomeownerFlag?: string | null;
  unitsCount: number;
  utilitiesSewageUsage: string;
  utilitiesWaterSource: string;
  yearBuilt: number;
};

type TaxInfo = {
  assessedImprovementValue: number;
  assessedLandValue: number;
  assessedValue: number;
  assessmentYear: number;
  estimatedValue?: string | null;
  marketImprovementValue: number;
  marketLandValue: number;
  marketValue: number;
  propertyId: number;
  taxAmount: string;
  taxDelinquentYear?: number | null;
  year: number;
};

export type SaleHistory = {
  book: any;
  page: any;
  documentNumber: number;
  armsLength: boolean;
  buyerNames: string;
  documentType: string;
  documentTypeCode: string;
  downPayment: number;
  ltv: number;
  ownerIndividual: boolean;
  purchaseMethod: string;
  recordingDate: string;
  saleAmount: number;
  saleDate: string;
  sellerNames: string;
  seqNo: number;
  transactionType: string;
};

export type MortgageHistory = {
  amount: number;
  assumable: boolean;
  book: null | string;
  page: null | string;
  documentNumber: null | string;
  deedType: string;
  documentDate: string;
  granteeName: string;
  interestRate: number;
  interestRateType: string;
  lenderCode: string;
  lenderName: string;
  lenderType: string;
  loanType: string;
  loanTypeCode: string;
  maturityDate: string;
  mortgageId: string;
  open: boolean;
  position: string;
  recordingDate: string;
  seqNo: number;
  term: number;
  termType: string;
  transactionType: string;
};

export type PropertyDetails = {
  id: number;
  MFH2to4: boolean;
  MFH5plus: boolean;
  absenteeOwner: boolean;
  adjustableRate: string | null;
  assumable: string | null;
  auction: boolean;
  equity: string | null;
  bankOwned: string | null;
  cashBuyer: string | null;
  cashSale: string | null;
  corporateOwned: boolean;
  death: string | null;
  deathTransfer: string | null;
  deedInLieu: string | null;
  equityPercent: number;
  estimatedEquity: number;
  estimatedMortgageBalance: string;
  estimatedMortgagePayment: string;
  estimatedValue: number;
  floodZone: boolean;
  floodZoneDescription: string;
  floodZoneType: string;
  freeClear: boolean;
  highEquity: boolean;
  inStateAbsenteeOwner: boolean;
  inherited: string | null;
  investorBuyer: boolean;
  judgment: boolean;
  lastSaleDate: string;
  lastSalePrice: string;
  lastUpdateDate: string;
  lien: string | null;
  loanTypeCodeFirst: string | null;
  loanTypeCodeSecond: string | null;
  loanTypeCodeThird: string | null;
  maturityDateFirst: string | null;
  mlsActive: boolean;
  mlsCancelled: boolean;
  mlsDaysOnMarket: number | null;
  mlsFailed: boolean;
  mlsFailedDate: string | null;
  mlsHasPhotos: boolean;
  mlsLastSaleDate: string | null;
  mlsLastStatusDate: string | null;
  mlsListingDate: string | null;
  mlsListingPrice: string | null;
  mlsListingPricePerSquareFoot: string | null;
  mlsPending: boolean;
  mlsSold: boolean;
  mlsSoldPrice: string | null;
  mlsStatus: string | null;
  mlsTotalUpdates: number | null;
  mlsType: string | null;
  mobileHome: boolean;
  noticeType: string | null;
  openMortgageBalance: number;
  outOfStateAbsenteeOwner: boolean;
  ownerOccupied: boolean;
  preForeclosure: boolean;
  privateLender: string | null;
  propertyType: string;
  quitClaim: string | null;
  reapi_loaded_at: string | null;
  sheriffsDeed: string | null;
  spousalDeath: string | null;
  taxLien: string | null;
  trusteeSale: string | null;
  vacant: boolean;
  warrantyDeed: string | null;
  auctionInfo: Record<string, any>;
  currentMortgages: any[];
  demographics: Demographics;
  foreclosureInfo: any[];
  lastSale: LastSale;
  linkedProperties: LinkedProperties;
  lotInfo: LotInfo;
  mlsHistory: any[];
  mlsKeywords: Record<string, any>;
  mortgageHistory: MortgageHistory[];
  neighborhood: Record<string, any>;
  ownerInfo: OwnerInfo;
  propertyInfo: PropertyInfo;
  saleHistory: SaleHistory[];
  schools: any[];
  taxInfo: TaxInfo;
  address: PropertyDetailsAddress;
  longitude: number;
  latitude: number;
};

export type TableHeaderType = {
  key: string;
  label: string;
  sortable?: boolean;
  secondKey?: string;
  thirdKey?: string;
  isActive?: boolean;
  render?: (row: Record<string, any>, index: number) => JSX.Element;
  tdClass?: string;
  thClass?: string;
};

export type RentComparables = {
  rent: number;
  rentRangeLow: number;
  rentRangeHigh: number;
  latitude: number;
  longitude: number;
  comparables: Comparable[];
  lastUpdated: string;
};

export type Comparable = {
  id: string;
  formattedAddress: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  state: string;
  zipCode: string;
  county: string;
  latitude: number;
  longitude: number;
  propertyType: string;
  bedrooms: number;
  bathrooms: number;
  squareFootage: number;
  lotSize?: number;
  yearBuilt: number;
  price: number;
  listingType: string;
  listedDate: string;
  removedDate?: string | null;
  lastSeenDate: string;
  daysOnMarket: number;
  distance: number;
  daysOld: number;
  correlation: number;
  indicator?: string;
};

export type SalesComparisonsArray = {
  salesComparisons: SalesComparison[];
};

export type SalesComparison = {
  id: number | string;
  absenteeOwner: boolean;
  address: Address;
  bathrooms: number;
  bedrooms: number;
  cashBuyer: boolean;
  corporateOwned: boolean;
  equityPercent: string;
  estimatedValue: number;
  inStateAbsenteeOwner: boolean;
  landUse: string;
  lastSaleAmount: number;
  lastSaleDate: string;
  latitude: number;
  lenderName: string;
  longitude: number;
  lotSquareFeet: string;
  mailAddress: Address;
  mlsDaysOnMarket: string;
  mlsLastSaleDate: string;
  mlsSoldPrice: number | string;
  openMortgageBalance: number | string;
  outOfStateAbsenteeOwner: boolean;
  owner1FirstName: string;
  owner1LastName: string;
  preForeclosure: boolean;
  privateLender: boolean;
  propertyId: string;
  propertyType: string;
  propertyUse: string;
  propertyUseCode: string;
  squareFeet: number;
  vacant: boolean;
  yearBuilt: string | number;
  indicator?: string;
};

export type Address = {
  address: string;
  city: string;
  county: string;
  state: string;
  street: string;
  zip: string;
};

export type LongLat = {
  lat: number;
  lng: number;
};
